# Generated by Django 5.2.3 on 2025-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
