# Generated by Django 5.2.3 on 2025-06-28 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_platform_icon_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='content_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UserGameInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('search', 'Search'), ('like', 'Like'), ('bookmark', 'Bookmark')], max_length=20)),
                ('interaction_weight', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.JSONField(default=dict)),
                ('preferred_platforms', models.JSONField(default=dict)),
                ('preferred_publishers', models.JSONField(default=dict)),
                ('preferred_tags', models.JSONField(default=dict)),
                ('avg_rating_preference', models.FloatField(default=0.0)),
                ('avg_metacritic_preference', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_similarity', models.FloatField(default=0.0)),
                ('collaborative_similarity', models.FloatField(default=0.0)),
                ('hybrid_similarity', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_from', to='games.game')),
                ('game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_to', to='games.game')),
            ],
            options={
                'unique_together': {('game1', 'game2')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('content', 'Content-Based'), ('collaborative', 'Collaborative'), ('hybrid', 'Hybrid'), ('popular', 'Popular'), ('trending', 'Trending')], max_length=20)),
                ('recommended_games', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recommendation_type')},
            },
        ),
        migrations.CreateModel(
            name='UserGameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
