# Generated by Django 5.2.3 on 2025-06-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_content_vector_game_popularity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='esrb',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
