# Generated by Django 5.2.3 on 2025-06-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_esrb'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='store_url',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
